tradewave/urls.py
from django.conf.urls import url, include
#from django.contrib.auth.models import User
from rest_framework import routers, viewsets
from tradewave import views

# Routers provide an easy way of automatically determining the URL conf.
#router = routers.DefaultRouter()
#router.register(r'accounts', views.account_list)

urlpatterns = [
    # API
    #url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/$', views.AccountList.as_view(), name='accounts'),
    url(r'^accounts/(?P<pk>[0-9]+)/$', views.AccountDetail.as_view()),
    url(r'^transaction-logs/$', views.TransactionLogList.as_view(), name='transaction-logs'),
    url(r'^transaction-logs/(?P<uuid>[\w-]+)/$', views.TransactionLogDetail.as_view()),
    url(r'^transaction-logs/entity/spent/(?P<account_id>\d+)/$', views.TransactionLogEntitySpentPandas.as_view(), name='transactions-spent'),
    url(r'^transaction-logs/entity/received/(?P<account_id>\d+)/$', views.TransactionLogEntityReceiviedPandas.as_view(), name='transactions-received'),

    # template views
    url(r'^$', views.LoginView.as_view(), name='root'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^login/(?P<status_msg>.*)/$', views.LoginView.as_view(), name='login'),
    url(r'^send/$', views.SendView.as_view(), name='send'),
    url(r'^confirm-send/$', views.ConfirmSendView.as_view(), name='confirm-send'),
    url(r'^confirm-receive/$', views.ConfirmReceiveView.as_view(), name='confirm-receive'),
    url(r'^create-user/$', views.CreateUser.as_view(), name='create-user'),
    url(r'^create-user/(?P<vendor_id>\d+)/(?P<vendor_name>\w+)/(?P<status_msg>.*)/$', views.CreateUser.as_view(), name='create-user-vendor'),
    url(r'^create-user-new/(?P<invite_token>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/$', views.CreateUserNew.as_view(), name='create-user-new'),
    url(r'^create-vendor/(?P<invite_token>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})$', views.CreateVendor.as_view(), name='create-vendor'),
    url(r'^create-vendor/(?P<invite_token>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<status_msg>.*)/$', views.CreateVendor.as_view(), name='create-vendor'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^entity-invite-or-assign-users/$', views.EntityInviteOrAssignUsers.as_view(), name='entity-invite-or-assign-users'),
    url(r'^marketplace-initial/$', views.MarketplaceInitial.as_view(), name='marketplace-initial'),
    url(r'^marketplace-invite-vendors/$', views.MarketplaceInviteVendors.as_view(), name='marketplace-invite-vendors'),
    url(r'^marketplace-issue/$', views.MarketplaceIssue.as_view(), name='marketplace-issue'),
    url(r'^marketplace-issue-login/$', views.MarketplaceIssueLogin.as_view(), name='marketplace-issue-login'),
    url(r'^marketplace-issue-login/(?P<status_msg>.*)/$', views.MarketplaceIssueLogin.as_view(), name='marketplace-issue-login'),
    url(r'^marketplace-issue-pick-credit/$', views.MarketplaceIssuePickCredit.as_view(), name='marketplace-issue-pick-credit'),
    url(r'^marketplace-redeem/$', views.MarketplaceRedeem.as_view(), name='marketplace-redeem'),
    url(r'^marketplace-redeem/(?P<status_msg>.*)/$', views.MarketplaceRedeem.as_view(), name='marketplace-redeem'),
    url(r'^marketplace-home/$', views.MarketplaceHome.as_view(), name='marketplace-home'),
    url(r'^marketplace-home/(?P<status_msg>.*)/$', views.MarketplaceHome.as_view(), name='marketplace-home-status'),
    url(r'^marketplace-theme/$', views.MarketplaceThemeView.as_view(), name='marketplace-theme'),
    url(r'^marketplace-send/$', views.MarketplaceSend.as_view(), name='marketplace-send'),
    url(r'^settings-user/$', views.SettingsUser.as_view(), name='settings-user'),
    url(r'^settings-vendor/$', views.SettingsVendor.as_view(), name='settings-vendor'),
    url(r'^settings-marketplace/$', views.SettingsMarketplace.as_view(), name='settings-marketplace'),
    url(r'^support/$', views.CustomerSupportView.as_view(), name='cust-support'),
    url(r'^transaction-confirmed/(?P<tr_amount>\d+\.\d{2})/(?P<amount>\d+\.\d{2})/(?P<sender_name>.*)/(?P<recipient_name>.*)/(?P<tr_type>\w+)$', views.TransactionConfirmedView.as_view(), name='transaction-confirmed'),
    url(r'^vendor-initial/$', views.VendorInitial.as_view(), name='vendor-initial'),
    url(r'^vendor-cust-login/$', views.VendorCustomerLogin.as_view(), name='vendor-cust-login'),
    url(r'^vendor-cust-login/(?P<status_msg>.*)/$', views.VendorCustomerLogin.as_view(), name='vendor-cust-login'),
    url(r'^vendor-choose-payment/$', views.VendorChoosePayment.as_view(), name='vendor-choose-payment'),
    url(r'^vendor-home/$', views.VendorHome.as_view(), name='vendor-home'),
    url(r'^vendor-home/$', views.VendorHome.as_view(), name='vendor-home-status'),
    url(r'^vendor-transaction/$', views.VendorTransaction.as_view(), name='vendor-transaction'),
    url(r'^vendor-transaction/(?P<status_msg>.*)/$', views.VendorTransaction.as_view(), name='vendor-transaction'),
    url(r'^user-home/$', views.UserHomeView.as_view(), name='user-home'),
    url(r'^user-home/(?P<status_msg>.*)/$', views.UserHomeView.as_view(), name='user-home-status'),
    url(r'^500/$', views.ErrorView.as_view(), name='500'),
    url(r'^404/$', views.NotFoundView.as_view(), name='404'),
    #url(r'^.*/$', views.LoginView.as_view(), name='login'),

    # functional views
    url(r'^assign_credit_to_user/$', views.assign_credit_to_user, name='assign_credit_to_user'),
    url(r'^create_user/$', views.create_user, name='create_user'),
    url(r'^create_vendor/(?P<token>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})$', views.create_vendor, name='create_vendor'),
    url(r'^entity_invite_or_assign_users/(?P<entity_id>\d+)/(?P<is_vendor>(True|False))$', views.entity_invite_or_assign_users, name='entity_invite_or_assign_users'),
    url(r'^export_data/$', views.export_data, name='export_data'),
    url(r'^process_cust_login/(?P<login_reason>(issue_credit|transaction))$', views.process_cust_login, name='process_cust_login'),
    url(r'^process_invite/(?P<token>[0-9a-f\-]{36})$', views.process_invite, name='process_invite'),
    url(r'^process_login/$', views.process_login, name='process_login'),
    url(r'^process_logout/$', views.process_logout, name='process_logout'),
    url(r'^process_signup/$', views.process_signup, name='process_signup'),
    url(r'^process_vendor_payment/$', views.process_vendor_payment, name='process_vendor_payment'),
    url(r'^process_vendor_transaction/$', views.process_vendor_transaction, name='process_vendor_transaction'),
    url(r'^record_venue/(?P<venue_id>\d+)/$', views.record_venue, name='record_venue'),
    url(r'^redeem_credits/$', views.redeem_credits, name='redeem_credits'),
    url(r'^redirect_to_vendor/$', views.redirect_to_vendor, name='redirect_to_vendor'),
    url(r'^redirect_to_marketplace/$', views.redirect_to_marketplace, name='redirect_to_marketplace'),
]

handler404 = 'tradewave.views.handler404'
handler500 = 'tradewave.views.handler500'
#handler403 = 'mysite.views.my_custom_permission_denied_view'
#handler400 = 'mysite.views.my_custom_bad_request_view'

tradewave_beta/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tradewave.urls', namespace="tradewave"))
]

tradewave/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, render_to_response
from django.views.generic import View, ListView, TemplateView
from django.template import RequestContext

from tradewave.models import \
    Venue, \
    TradewaveUser, \
    Entity, EntityVenues, \
    Vendor, \
    Marketplace, MarketplaceVendors, \
    Credit, Account, CreditMap, TransactionLog, \
    Product, \
    Token


from tradewave.forms import \
    AssignCreditToUserForm, \
    EntityInviteOrAssignUsersForm, \
    CreateUserForm, \
    CreateVendorForm, \
    DataExportForm, \
    LoginUserForm, \
    RedeemVendorsForm, \
    VendorTransactionForm, \
    VendorPaymentForm

from tradewave.allocations import CreditAllocations
from tradewave.exceptions import CustomerInvalidCredentialsException
from tradewave.serializers import AccountSerializer, TransactionLogSerializer
from tradewave.tasks import sendTransactionalEmail
from tradewave.token import TokenRecord
from tradewave.transaction import TradewaveTransaction
from tradewave.twuser import TwUser
from tradewave.wallet import Wallet

from collections import OrderedDict
from datetime import datetime, timedelta
from decimal import Decimal
from import_export import resources

from rest_framework import generics
from rest_framework import permissions

from rest_pandas import PandasView

import logging
import pytz
import uuid


logging.basicConfig(level=logging.DEBUG, filename="log/views.log")
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


# *** API ***
class AccountList(generics.ListCreateAPIView):
    """
    List all accounts, or create a new account.
    """
    queryset = Account.objects.all()
    serializer_class = AccountSerializer


class AccountDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve / update / destroy an account.
    """
    queryset = Account.objects.all()
    serializer_class = AccountSerializer


# *** API ***
class TransactionLogList(generics.ListCreateAPIView):
    """
    List all accounts, or create a new transaction log.
    """
    queryset = TransactionLog.objects.all()
    serializer_class = TransactionLogSerializer


class TransactionLogDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve / update / destroy an account.
    """
    queryset = TransactionLog.objects.all()
    serializer_class = TransactionLogSerializer
    lookup_field = 'uuid'


class TransactionLogEntitySpentDetail(generics.ListAPIView):
    """
    Retrieve transactions for a given entity
    """
    serializer_class = TransactionLogSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    lookup_url_kwarg = "account_id"

    def get_queryset(self):
        account_id = self.kwargs.get(self.lookup_url_kwarg)
        transactions = TransactionLog.objects.filter(transact_from=account_id)

        before = self.request.query_params.get('before', None)
        if before:
            transactions = transactions.filter(
                date_transacted__lte=datetime.fromtimestamp(float(before))
            )

        after = self.request.query_params.get('after', None)
        if after:
            transactions = transactions.filter(
                date_transacted__gte=datetime.fromtimestamp(float(after))
            )
        return transactions


class TransactionLogEntityReceivedDetail(generics.ListAPIView):
    """
    Retrieve transactions for a given entity
    """
    serializer_class = TransactionLogSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    lookup_url_kwarg = "account_id"

    def get_queryset(self):
        account_id = self.kwargs.get(self.lookup_url_kwarg)
        transactions = TransactionLog.objects.filter(transact_to=account_id)

        before = self.request.query_params.get('before', None)
        if before:
            transactions = transactions.filter(
                date_transacted__lte=datetime.fromtimestamp(float(before))
            )

        after = self.request.query_params.get('after', None)
        if after:
            transactions = transactions.filter(
                date_transacted__gte=datetime.fromtimestamp(float(after))
            )
        return transactions


class TransactionLogEntitySpentPandas(PandasView):
    """
    Retrieve outgoing transactions for a given entity
    """
    serializer_class = TransactionLogSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = TransactionLog.objects.all()

    def filter_queryset(self, qs):
        account_id = self.kwargs.get('account_id')
        qs = TransactionLog.objects.filter(transact_from=account_id)
        before = self.request.query_params.get('before', None)
        if before:
            qs = qs.filter(
                date_transacted__lte=datetime.fromtimestamp(float(before))
            )

        after = self.request.query_params.get('after', None)
        if after:
            qs = qs.filter(
                date_transacted__gte=datetime.fromtimestamp(float(after))
            )
        return qs


class TransactionLogEntityReceiviedPandas(PandasView):
    """
    Retrieve incoming transactions for a given entity
    """
    serializer_class = TransactionLogSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = TransactionLog.objects.all()

    def filter_queryset(self, qs):
        account_id = self.kwargs.get('account_id')
        qs = TransactionLog.objects.filter(transact_to=account_id)
        before = self.request.query_params.get('before', None)
        if before:
            qs = qs.filter(
                date_transacted__lte=datetime.fromtimestamp(float(before))
            )

        after = self.request.query_params.get('after', None)
        if after:
            qs = qs.filter(
                date_transacted__gte=datetime.fromtimestamp(float(after))
            )
        return qs


# *** class view ***
# Global session variables:
#   *) user_id
#   *) entity_id
#   *) entity_personal_id
#   *) entity_customer_id

# Known limitations:
#   1) A single account per entity type

class IndexView(ListView):
    model = User
    template_name = 'tradewave/index.html'


class SessionContextView(View):
    def get_context_data(self, **kwargs):
        context = super(SessionContextView, self).get_context_data(**kwargs)
        session = self.request.session

        # TODO: restric to items used in templates
        for key, val in session.iteritems():
            context[key] = val

        context['user_id'] = self.request.user.id
        return context


class LoginView(SessionContextView, TemplateView):
    template_name = 'tradewave/login.html'


class ErrorView(SessionContextView, TemplateView):
    template_name = 'tradewave/500.html'


class NotFoundView(SessionContextView, TemplateView):
    template_name = 'tradewave/404.html'


class SendView(ListView):
    model = User
    template_name = 'tradewave/send.html'


class ConfirmSendView(ListView):
    model = User
    template_name = 'tradewave/confirm-send.html'


class ConfirmReceiveView(ListView):
    model = User
    template_name = 'tradewave/confirm-receive.html'


class CustomerSupportView(SessionContextView, TemplateView):
    template_name = 'tradewave/cust-support.html'


class TransactionConfirmedView(LoginRequiredMixin, PermissionRequiredMixin, SessionContextView, TemplateView):
    template_name = 'tradewave/transaction-confirmed.html'
    permission_required = 'tradewave.can_transact'

    def get_context_data(self, **kwargs):
        context = super(TransactionConfirmedView, self).get_context_data(**kwargs)
        context['tr_amount'] = float(context['tr_amount'])
        context['amount'] = float(context['amount'])

        return context


# these should be some temporary users until they are confirmed
class CreateUser(SessionContextView, TemplateView):
    template_name = 'tradewave/create-user.html'


# anonymous requests with an invite token
class CreateUserNew(SessionContextView, TemplateView):
    template_name = 'tradewave/create-user.html'

    def get(self, request, *args, **kwargs):
        context = super(CreateUserNew, self).get_context_data(**kwargs)

        invite_token = context['invite_token']
        token_record = TokenRecord(invite_token)
        if token_record.is_valid():
            context['user_email'] = token_record.get_email()
            return render(request, self.template_name, context)
        else:
            error_msg = 'Invalid token: %s'
            logger.warning(error_msg, invite_token)
            return redirect(
                'tradewave:login',
                status_msg=error_msg % invite_token
            )


# anonymous request with a marketplace invite token
class CreateVendor(SessionContextView, TemplateView):
    template_name = 'tradewave/create-vendor.html'

    def get(self, request, *args, **kwargs):
        context = super(CreateVendor, self).get_context_data(**kwargs)

        invite_token = context['invite_token']
        token_record = TokenRecord(invite_token)
        marketplace = token_record.get_entity()

        if token_record.is_valid() and marketplace:
            context['marketplace_venues'] = dict([
                (item.id, item.name) for item in marketplace.venues.all()
            ])
            context['product_categories'] = dict([
                (item.id, item.name) for item in Product.objects.all()
            ])
            return render(request, self.template_name, context)
        else:
            error_msg = 'Invalid token: %s'

tradewave/templates/tradewave/dashboard.html
{% extends "tradewave/base.html" %}

{% load staticfiles %}

{% block title %} {{ entity_name }} {% endblock %}

{% block content %}

  <script src="https://d3js.org/d3.v3.min.js"></script>
  <script src="{% static "js/jquery-ui.min.js" %}"></script>

  <style>

  .chart rect {
    fill: steelblue;
  }

  .chart text {
    fill: white;
    font: 10px sans-serif;
    text-anchor: end;
  }

  </style>

  <section id="intro">
    {% if entity_marketplace %}
      <form method="post" action="{% url 'tradewave:export_data' %}">
        {% csrf_token %}
        <div class="row">
          <div class="left input-left small-6 columns">
            <label for="market_venue">
              Market venue:
            </label>
            <select name="market_venue" class="text" id="market_venue">
              {% for market_venue in market_venues %}
                  <option class="text" value="{{market_venue}}"> {{market_venue}} </option>
              {% endfor %}
            </select>
          </div>

          <div class="left input-right small-6 columns">
            <label for="vendor">
              Vendor:
            </label>
            <select name="vendor" class="text">
              {% for vendor in vendors %}
                  <option class="text" value="{{vendor}}"
                    {% if vendor == "All" %}
                      selected="selected"
                    {% endif %}>
                      {{vendor}}
                  </option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="row">
          <div class="left small-5 columns">
            <label for="market_start_date">
              Start date:
            </label>
            <input required type="text" name="market_start_date" id="market_start_date"/>
          </div>

          <div class="relative small-2 columns">
            <p class="two-margin-top">to</p>
          </div>

          <div class="right small-5 columns">
            <label for="market_end_date">
              End date:
            </label>
            <input required type="text" name="market_end_date" id="market_end_date"/>
          </div>
        </div>

        <div class="row">
          <div class="left small-6 small-centered columns">
            <label for="credit_type">
              Credit type:
            </label>
            <select name="credit_type" class="text" id="credit_type">
              {% for credit_type in credit_types %}
                  <option class="text" value="{{credit_type}}"
                    {% if credit_type == "All" %}
                      selected="selected"
                    {% endif %}>
                      {{credit_type}}
                  </option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="row half-margin-top one-margin-bottom">
          <input type="submit" class="button" id="button_export_data" value="Export Market Data"/>
          <!--a href="{% url 'tradewave:export_data' %}" class="button button-style1 button-big"> Export Market Data  </a-->
        </div>
      </form>
    {% endif %}

    <div class="row half">
      <div class="12u">
        <p class="style3">
          Your Account Transactions:
        </p>
      </div>
    </div>
    <svg class="chart"></svg>

    <script type="text/javascript">
      $('#market_start_date, #market_end_date').datepicker();
    </script>

    <script>
      // TODO: Make this a reactive select element to allow the user
      // to choose whether to display the dashboard for their personal
      // or entity accounts
      var arraySpentReceivedUrls = [
        "{% url 'tradewave:transactions-spent' account_entity_id %}",
        "{% url 'tradewave:transactions-received' account_entity_id %}"
      ];
      arraySpentReceivedUrls.forEach(function (tr_url) {
        var width = 420,
            barHeight = 20;

        var x = d3.scale.linear()
            .range([0, width]);

        var chart = d3.select(".chart")
            .attr("width", width);

        d3.csv(tr_url, function(error, data) {
          x.domain([0, d3.max(data, function(d) { return Number(d.amount) + 20; })]);
          chart.attr("height", barHeight * data.length);

          var bar = chart.selectAll("g")
              .data(data)
            .enter().append("g")
              .attr("transform", function(d, i) { return "translate(0," + i * barHeight + ")"; });

          bar.append("rect")
              .attr("width", function(d) { return x(d.amount); })
              .attr("height", barHeight - 1)
              .style("fill", function (d) {
                if (Number(d.transact_to) === {{ account_entity_id }}) {
                  console.log(d.transact_to + '=>' + d.transact_from);
                  return "lightsteelblue";
                }
                else {
                  console.log(d.transact_to + '=>' + d.transact_from);
                  return "lightsalmon";
                }
              });

          bar.append("text")
              .attr("x", function(d) { return x(d.amount) + 30; })
              .attr("y", barHeight / 2)
              .attr("dy", ".35em")
              .style("fill", "black")
              .text(function(d) { return d.amount; });
        });

      });

      function type(d) {
        d.amount = +d.amount; // coerce to number
        return d;
      }
    </script>

    <!--script>
      d3.select(".chart")
        .selectAll("div")
        .csv("http://localhost:8000/transaction-logs/entity/spent/2/?before=1468224984&after=1467879384")
        .enter().append("div").
        .style
    </script-->

  </section>
{% endblock %}

tradewave/templates/tradewave/login.html
{% extends "tradewave/base.html" %}

{% block title %} Log in {% endblock %}

{% block content %}
  <section id="intro">
    <!-- Login Form -->
    <form method="post" action="{% url "tradewave:process_login" %}">
      {% csrf_token %}
      <div class="row">
        <div class="medium-8 small-centered columns ">
          <input type="text" class="text" name="user_name" id="user-email" placeholder="Email / Username" />
          <input type="password" class="text" name="user_password" id="user-password" placeholder="Password" />
        </div>
      </div>
      <div class="row center">
        <input type="submit" class="one-margin-top button large" value="Login" />
        <p class="lead">or <a class="signup-box_open">Sign up</a></p>
      </div>
    </form>
    <!-- /Login Form -->

  </section>

  <div id="signup-box" class="modal center small-12 medium-9 large-7 small-centered columns">
    <div class="row center">
      <h3 class="one-margin-top two-margin-bottom">Sign up</h3>
    </div>

    <div class="row center">
      <form action="{% url "tradewave:process_signup" %}">
        {% csrf_token %}        
        <div class="small-centered medium-10 columns">
          <div class="input-left small-6 columns">
            <input type="text" name="user_firstname" placeholder="First name" tabindex="1" />
          </div>

          <div class="input-right small-6 columns">
            <input type="text" name="user_lastname" placeholder="Last name" tabindex="2" />
          </div>

          <div class="small-12 columns">
            <input type="email" name="user_email" placeholder="Email address" tabindex="3" />
          </div>

          <div class="input-left small-6 columns">
            <input type="text" name="user_password" placeholder="Password" tabindex="4" />
          </div>

          <div class="input-right small-6 columns">
            <input type="text" name="verify_password" placeholder="Verify password" tabindex="5" />
          </div>

          <button type="submit" class="one-margin-top button">Create account</button>
          <p><a class="signup-box_close">Cancel</a></p>
        </div>
      </form>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function(){
      $('#signup-box').popup({
        vertical: 'top',
        transition: 'all 0.75s',
        scrolllock: true,
      });
    });
  </script>
{% endblock %}

tradewave/templates/tradewave/marketplace-invite-vendors.html
{% extends "tradewave/base.html" %}

{% block title %}
  Invite vendors to {{ name }}
{% endblock %}

{% block content %}

  <!-- User Form -->
  <form method="post" action="{% url 'tradewave:entity_invite_or_assign_users' entity_id=entity_id is_vendor=True %}">
    {% csrf_token %}
    <div class="row">
      <p>Add emails of vendors you wish to invite:</p>
    </div>

    <div id="assign-emails" class="row">
      <div class="medium-8 medium-offset-2 column end">
        <input type="email" name="user_emails" id="user-email-1" placeholder="Vendor Email"/>
      </div>
    </div>
    <div class="row">
      <p><a id="add-user-email">Add vendor email</a></p>
    </div>

    <div class="row">
      <input type="submit" class="button" value="Invite"/>
    </div>

  </form>

  <script type="text/javascript">
    $(document).ready(function(){
      var num = 1;
      $('#add-user-email').click(function(){
        num++;
        $('#assign-emails').append('<div class="medium-8 medium-offset-2 column end"><input type="email" name="user_emails" id="user-email-'+num+'" placeholder="Vendor Email"/></div>');
      });
    });
  </script>
{% endblock %}

tradewave/templates/tradewave/marketplace-issue-pick-credit.html
{% extends "tradewave/base.html" %}

{% block title %}
  Issue Credits
  <h6>Pick credit type and amount to assign to <strong>{{ entity_customer }}</strong>:</h6>


{% endblock %}

{% block content %}
  <section id="intro">
    <!-- Login Form -->
    <!-- change / adapt the action link to issuing credits -->
    <form method="post" action="{% url 'tradewave:assign_credit_to_user'%}">
      {% csrf_token %}
      <div class="row one-margin-bottom">
        <div class="small-12 medium-6 columns">
          <select name="credit_uuid" >
            {% for credit_uuid, credit_data in marketplace_credits.items %}
                <option class="text" value="{{credit_uuid}}"> {{credit_data.name}} </option>
            {% endfor %}
          </select>
        </div>

        <div class="small-12 medium-6 columns">
          <input
            type="number"
            class="text"
            min="0.01"
            step="0.01"
            name="credit_amount"
            id="credit-amount"
            placeholder="Enter amount"/>
        </div>
      </div>

      <div class="row">
        <input type="submit" class="button button-style1 button-big" value="Assign credit" />
        <a href="{% url 'tradewave:marketplace-issue'%}" class="button secondary">Cancel</a>
      </div>
    </form>
    <!-- /Login Form -->

  </section>
{% endblock %}

tradewave/templates/tradewave/marketplace-theme.html
{% extends "tradewave/base.html" %}

{% load staticfiles %}

{% block title %}
  Customize theme 
  <h5 class="half-margin-top">for {{ name }}</h5>
{% endblock %}

{% block content %}
  <section id="intro">
    <div class="row half-margin-bottom">
      <div class="center medium-10 small-centered columns">
        <p class="">Please upload an image that you would like to be displayed in your header. For best results, use an image at least 180 x 60px with a 3:1 aspect ratio.</p>

        <input type="file" name="custom_logo" id="custom_logo" accept=".png .jpg" class="inputfile" />
        <label for="custom_logo" class="button secondary">Upload image</label>

        <p class="one-margin-top">Also, select a main color. This will look best if it matches the background color of your logo, or if your logo has a transparent background.</p>

        <script src="{% static 'js/jscolor.min.js' %}"></script>
        <input type="text" id="color-input" class="jscolor center" value="387a36"/>
        <p><button id="color-reset" class="one-margin-top button secondary small">Reset color</button></p>

        <input type="submit" class="button" value="Save"/>
      </div>
    </div>

  </section>

  <script type="text/javascript">

    var reset_color = "387A36";
    $('#color-reset').click(function(){
      $('#color-input').val(reset_color).focus().blur();
    });
  </script>
{% endblock %}